apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    frontend http_front
      bind *:80
      default_backend tomcat_backend

    backend tomcat_backend
      balance roundrobin
      server tomcat1 tomcat-service:8080 check
